##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
users:
  - { name: yujunz, comment: "Yujun Zhang <zhang.yujunz@zte.com.cn>" }
  - { name: taseer, comment: "Taseer Ahmed <taseer94@gmail.com>" }
  - { name: serena, comment: "Serena Feng <feng.xiaowei@zte.com.cn>" }
  - { name: zhifeng, comment: "Zhifeng Jiang<jiang.zhifeng@zte.com.cn>" }
  - { name: akhil, comment: "Akhil Batra<akhil.batra@research.iiit.ac.in"}
