---

- hosts: elk
  gather_facts: no

  tasks: 
   - name: Adding Keys
     sudo: yes
     shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

   - name: Adding Entry for Ubuntu
     shell: echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
     when: ansible_distribution == "Ubuntu" and ansible_release == "Xenial" and ansible_version == "16.04"

   - name: Installing from Docker Repo
     shell: sudo apt-cache policy docker-engine
     when: ansible_distribution == "Ubuntu" and ansible_release == "Xenial" and ansible_version == "16.04"

   - name: Adding Entry for Ubuntu
     shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
     when: ansible_distribution == "Ubuntu" and ansible_release == "Trusty-Tahr" and ansible_version == "14.04"

   - name: Updating
     shell: sudo apt-get update

   - name: Installing Docker-Engine
     shell: sudo apt-get install docker-engine

   - name: Starting Docker Service
     shell: sudo service docker start

   - name: Pulling ElasticSearch
     shell: sudo docker pull elasticsearch

   - name: Setting Up ElasticSearch
     shell: sudo docker run -d -p 9200:9200 --name esearch elasticsearch

   - name: Pulling Kibana
     shell: sudo docker pull kibana

   - name: Setting Up Kibana
     shell: sudo docker run --link esearch:elasticsearch -p 5601:5601 --name kibana -d kibana
