##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Checking home directory
      shell: echo $HOME
      register: home_dir

    - name: Cleaning tempT
      file:
        path: '{{ home_dir.stdout }}/tempT'
        state: absent

    - name: Cleaning qtip_result
      file:
        path: '{{ home_dir.stdout }}/qtip_result'
        state: absent
