##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


- name: get ceph disk ,ceph journal information 
  shell: ceph-disk list ; lsblk -d -o name,rota |awk '{if ($2 == 0)  printf "%s SSD \n",$1 }'
  register: ceph_disk_out

- name: saving output to log
  copy:
    content: "{{ ceph_disk_out.stdout }}"
    dest: "{{ logfile }}"
  delegate_to: localhost

- name: get ceph report
  command: ceph report
  register: ceph_report_out

- name: saving ceph report to log
  copy:
    content: "{{ ceph_report_out.stdout }}"
    dest: "{{ output }}/ceph_report.json"
  delegate_to: localhost
