##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: calculate compute score
  calculate:
    metrics:
      ssl_rsa: "{{ qtip_results }}/ssl/rsa-metrics.json"
      ssl_aes: "{{ qtip_results }}/ssl/aes-metrics.json"
      dpi_throughput: "{{ qtip_results }}/dpi/metrics.json"
      intmem: "{{ qtip_results }}/memory/integer-metrics.json"
      floatmem: "{{ qtip_results }}/memory/float-metrics.json"
      arithmetic: "{{ qtip_results }}/arithmetic/metrics.json"
    sysinfo: "{{ qtip_results }}/sysinfo/condition.json"
    spec:   "{{ qtip_resources }}/QPI/compute.yaml"
    baseline: "{{ qtip_resources }}/QPI/compute-baseline.json"
    dest: "{{ qtip_results }}/compute.json"
  delegate_to: localhost
