##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: gathering overcloud baremetal info
  shell: "source {{ ansible_env.HOME}}/stackrc && openstack baremetal list --fields instance_uuid properties provision_state --format json"
  register: baremetal_info

- name: gathering overcloud server info
  shell: "source {{ ansible_env.HOME }}/stackrc && openstack server list --format json"
  register: server_info

- name: generating inventory
  apex_generate_inventory:
    baremetal_info: "{{ baremetal_info.stdout | from_json }}"
    server_info: "{{ server_info.stdout | from_json }}"
