##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
- name: installing software properties common
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common

- name: adding ubuntu backport main repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}}-backports  main restricted universe multiverse
    - deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} main restricted universe multiverse

- name: installing dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - python-selinux
    - libpcap-dev
    - libtool-bin
    - autoconf
    - automake
