##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: overriding result directory name
  set_fact:
    qtip_results: "{{ qtip_results }}/current/{{ inventory_hostname }}"
  tags:
    - always

- name: creating result directory
  file:
    path: "{{ qtip_results }}"
    state: directory
  delegate_to: localhost

- name: creating work directory
  file:
    path: "{{ qtip_workdir }}"
    state: directory

- import_tasks: install-deps.yml
