##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
  when: sut == vnf

- name: check whether install python 2 in target
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
  when: sut == vnf

- name: gather facts
  setup:

- name: overriding result directory name
  set_fact:
    qtip_results: "{{ qtip_results }}/current/{{ inventory_hostname }}"
  tags:
    - always

- name: creating result directory
  file:
    path: "{{ qtip_results }}"
    state: directory
  delegate_to: localhost

- name: creating work directory
  file:
    path: "{{ qtip_workdir }}"
    state: directory

- import_tasks: install-deps.yml
