heat_template_version: 2015-04-30

description: >
  Used to run VMs for Qtip

parameters:
  image:
    type: string
    description: Name of the image
    default: QTIP_CentOS

  timeout:
    type: number
    description: Timeout in seconds for WaitCondition, depends on your image and environment
    default: 900

  external_net_name:
    type: string
    description: Name of the external network which management network will connect to
    default: admin_floating_net

resources:
  flavor:
    type: OS::Nova::Flavor
    properties:
      ram: 8192
      vcpus: 8
      disk: 80

  network:
    type: OS::Neutron::Net
    properties:
      name: qtip_net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: qtip_subnet
      ip_version: 4
      cidr: 192.168.0.0/24
      network: { get_resource: network }

  management_router:
    type: OS::Neutron::Router
    properties:
      name: management_router
      external_gateway_info:
        network: { get_param: external_net_name }

  management_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: management_router }
      subnet: { get_resource: subnet }

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: qtip-key
      public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFWkAL5DwtPJ+0BMKBUcgq8ORdjMcj/wJl4qVVYeUdQDT/oS6pKuHNuk7BJpCLYLfHgSzO+Hv8J+5UyqXXXJKGxfAUPtpXrHRgburwhRJwcgtQVqWbQXHnY2jsikHeWWW5RX6SHxrLrxX04a8xmtD7BbDiJ6HZqVSem8XC15eZvw1C1dbqmbZqWBRWLFzhHf/9goucaSP3ekYWVCUPPlDS+D7r2Mc2Ch0Z7AivEJZ5mTamefS80B1ZNBRObvP/W5jPoAh5H9bHrqayZyEVGaYOk/toddJJAQHJIXu/8YSxnUnC0FbTtZ5s2JO/3Big5/IpW5m5NsHCOqVPjHkKkgkT root@foreman-jump.opnfv.com

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: qtip_security_group
      rules:
          - port_range_min: 22
            port_range_max: 5201
            protocol: tcp
          - port_range_min: 22
            port_range_max: 5201
            protocol: udp
          - protocol: icmp

outputs:
  description: 'none'

