##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: adding keys
  become: true
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net id=0X58118E89F3A912897C070ADBF76221572C52609D

- name: adding entry for ubuntu
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present filename='docker'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

- name: installing from docker repo
  become: true
  shell: apt-cache policy docker-engine
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version== "16.04"

- name: adding entry for ubuntu
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present filename='docker'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: updating
  become: true
  apt: update_cache=yes

- name: installing docker engine
  become: true
  apt: name=docker-engine
  notify:
    - starting docker service

- name: install pip
  become: true
  apt: name={{item}} state=installed
  with_items:
    - python-dev
    - python-pip

- name: install docker-py
  become: true
  pip:
    name: docker-py
    version: 1.7.0
