##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- hosts: localhost

  roles:
  # prepare local environment
  - { role: qtip, tasks: setup-local, tags: [setup] }


- hosts: SUT
  gather_facts: no
  pre_tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
      when: sut == vnf
    - name: check whether install python 2 in target
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
      when: sut == vnf
    - name: gather facts
      setup:

  roles:
  # prepare environment
  - { role: qtip, tasks: setup-node, tags: [setup] }


- hosts: SUT

  roles:
  # run test and collect metrics
    - { role: inxi, output: "{% raw %}{{ qtip_results }}{% endraw %}/sysinfo", tags: [run, inxi, sysinfo] }
    - { role: unixbench, output: "{% raw %}{{ qtip_results }}{% endraw %}/arithmetic", tags: [run, unixbench, arithmetic] }
    - { role: openssl, output: "{% raw %}{{ qtip_results }}{% endraw %}/ssl", tags: [run, openssl, ssl] }
    - { role: nDPI, output: "{% raw %}{{ qtip_results }}{% endraw %}/dpi", tags: [run, ndpi, dpi] }
    - { role: ramspeed, output: "{% raw %}{{ qtip_results }}{% endraw %}/memory", tags: [run, ramspeed, memory] }
  # calculate scores
    - { role: qtip, tasks: calculate, tags: [calculate] }


- hosts: localhost

  roles:
  # aggregate results and produce report
    - { role: qtip, tasks: aggregate, tags: [aggregate] }
  # publish results
    - { role: opnfv-testapi, tasks: report, when: testapi_url is defined, tags: [report] }
