##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


- name: preparing stack for storperf testing
  local_action: "shell {{ role_path }}/files/prepare.sh chdir={{ output }}"

- name: running storperf testing
  local_action: "shell {{ role_path }}/files/start_job.sh chdir={{ output }}"
