---
- name: adding keys
  become: true
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net id=0X58118E89F3A912897C070ADBF76221572C52609D

- name: adding entry for ubuntu
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present filename='docker'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

- name: installing from docker repo
  become: true
  shell: apt-cache policy docker-engine
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version== "16.04"

- name: adding entry for ubuntu
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present filename='docker'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: updating
  become: true
  apt: update_cache=yes

- name: installing docker engine
  become: true
  apt: name=docker-engine

- name: install pip
  apt:
    pkg: pip
    state: installed
  with_items:
    - python-dev
    - python-pip

- name: install docker-py
  pip:
    name: docker-py

- name: pulling elasticsearch and kibana
  become: true
  docker_image: name={{ item }} state=present
  with_items:
    - elasticsearch
    - kibana

- name: setting up elasticsearch
  become: true
  docker_container:
    name: esearch
    image: elasticsearch
    published_ports: 9200:9200

- name: setting up kibana
  become: true
  docker_container:
    name: kibana
    image: kibana
    published_ports: 5601:5601
    links: esearch:elasticsearch

- name: nginx is installed
  become: true
  package: name=nginx state=present
- name: qtip server configuration is generated
  become: true
  template: src={{ item }}.conf.j2 dest=/etc/nginx/sites-enabled/{{ item }}.conf
  with_items:
    - elk
  notify:
    - restart nginx
