---
- name: pulling elasticsearch and kibana
  become: true
  docker_image: name={{ item }} state=present
  with_items:
    - elasticsearch
    - kibana

- name: setting up elasticsearch
  become: true
  docker_container:
    name: esearch
    image: elasticsearch
    published_ports: 9200:9200

- name: setting up kibana
  become: true
  docker_container:
    name: kibana
    image: kibana
    published_ports: 5601:5601
    links: esearch:elasticsearch
