# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='github_link',
            field=models.URLField(unique=True),
        ),
    ]
