# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0002_auto_20170713_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
