# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0004_auto_20170715_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='github_link',
            new_name='git_link',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='log',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='run_time',
            field=models.DurationField(null=True),
        ),
    ]
