# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0005_auto_20170720_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In progress'), ('F', 'Finished')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='log',
            field=models.FileField(upload_to='logs'),
        ),
    ]
