##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- hosts: localhost

  roles:
  # prepare local environment
  - { role: qtip, tasks: setup-local, tags: [setup] }


- hosts: SUT

  roles:
  # prepare environment
  - { role: qtip, tasks: setup-node, tags: [setup] }


- hosts: SUT
  vars:
    - output: "{{ qtip_results }}"

  roles:
  # run test and collect metrics
    - ceph-cache-info
    - ceph-disk-info
    - ceph-network-info
