##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- fetch:
    src: /etc/ceph/ceph.conf
    dest: "{{ output }}/"
    flat: yes

- name: collect ceph catch info from ceph.conf
  set_fact: {"{{ item }}":"{{ lookup('ini', '{{ item }} section=client default='' file={{ output }}/ceph.conf')  }}"}
  with_items:
      - rbd_cache
      - rbd_cache_max_dirty
      - rdb_cache_size
  delegate_to: localhost
  ignore_errors: True
  register: result

- name: saving output to log
  copy:
    content: "{{ item }} {{ item.stdout }}"
    dest: "{{ logfile }}"
  when: result|succeeded
  delegate_to: localhost
  with_items:
      - rbd_cache
      - rbd_cache_max_dirty
      - rdb_cache_size
