##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: Install bwm-ng when CentOS
  yum:
    name: bwm-ng
    state: present
  when: ansible_os_family == "RedHat"

- name: Install bwm-ng when Ubuntu
  apt:
    name: bwm-ng
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Run bwm-ng
  shell: bwm-ng -o plain -c 1 > bwm-dump.log
  args:
    chdir: '{{ dest_path }}'