From: Cristina Pauna <cristina.pauna@enea.com>
Date: Thu, 9 Mar 2017 13:56:40 +0200
Subject: [PATCH] Apply aarch64 to Dockerfile

This patch adapts the Dockerfile so that the qtip image
can be build on an aarch64 machine

Signed-off-by: Cristina Pauna <cristina.pauna@enea.com>
---
 docker/Dockerfile | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/docker/Dockerfile b/docker/Dockerfile
index 1366513..5803b3d 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -2,8 +2,8 @@
 #####Docker container for QTIP############
 ##########################################

-FROM ubuntu:16.04
-MAINTAINER Yujun Zhang <zhang.yujunz@zte.com.cn>
+FROM aarch64/ubuntu:16.04
+MAINTAINER Armband team <armband@enea.com>
 LABEL version="0.1" description="OPNFV QTIP Docker container"

 ARG BRANCH=master
