##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# taseer94@gmail.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: create qtip stack
  os_stack:
    name: "{{ stack_name }}"
    state: present
    template: ../template/heat_template.yml
    endpoint_type: admin
    parameters:
      image_name: "{{ image_name }}"
      flavor_name: "{{ flavor_name }}"
      net_name: "{{ net_name }}"
      subnet_name: "{{ subnet_name }}"
      instance_name: "{{ inst_name }}"
    timeout: 600
