##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: nginx is installed
  become: true
  package: name=nginx state=present
- name: qtip server configuration is generated
  become: true
  template: src={{ item }}.conf.j2 dest=/etc/nginx/sites-enabled/{{ item }}.conf
  with_items:
    - elk
    - qtip
    - testapi
  notify:
    - restart nginx
