##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
- hosts: localhost

  gather_facts: no

  vars_prompt:

    - name: pod_name
      prompt: 'name of the pod under test:'
      default: qtip-pod
      private: no

    - name: scenario
      prompt: 'scenario deployed in the pod:'
      default: generic
      private: no

    - name: installer
      prompt: 'installer type of the pod (apex|fuel):'
      default: fuel
      private: no

    - name: installer_master_host
      prompt: 'master host of the installer:'
      default: master
      private: no

    - name: workspace
      prompt: 'workspace name:'
      default: workspace

  roles:

    - role: qtip-workspace

      # modify or override variables to customize the workspace

      # opnfv environment

#      installer: apex         # <fuel|apex>
#      installer_master_host: apex-virtual    # make sure you can login it with key authentication

      # set testapi_url to enable reportint to testapi

#      testapi_url: http://localhost:8000/api/v1

      # report variables

#      project_name: qtip
#      case_name: compute
#      pod_name: "{{ pod_name|default('qtip-pod') }}"
#      scenario: "{{ scenario|default('generic') }}"
#      version: master
#      scenario: demo

      # qtip settings

      qtip_package: ../../..  # relative path from **workspace**, not current directory
