##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

qtip_resources: "/Users/yujunz/Develop/qtip/qtip/cli/../../resources"
qtip_results: results
qtip_fixtures: fixtures
qtip_dump: dump
qtip_cache: ".qtip-cache"
qtip_workdir: "{{ ansible_env.HOME }}/qtip-workdir-20170809-1550"

installer_type: "apex"
installer_host: "apex-virtual-pod4"
installer_group:
  manual: dummy-group
  fuel: fuel-masters
  apex: apex-underclouds
