##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- hosts: localhost

  roles:
  # prepare local environment
  - { role: qtip, tasks: setup-local, tags: [setup] }


- hosts: compute

  roles:
  # prepare environment
  - { role: qtip, tasks: setup-node, tags: [setup] }


- hosts: compute

  roles:
  # run test and collect metrics
    - { role: inxi, output: "{{ qtip_results }}/sysinfo", tags: [run, inxi, sysinfo] }
    - { role: unixbench, output: "{{ qtip_results }}/arithmetic", tags: [run, unixbench, arithmetic] }
    - { role: openssl, output: "{{ qtip_results }}/ssl", tags: [run, openssl, ssl] }
    - { role: nDPI, output: "{{ qtip_results }}/dpi", tags: [run, ndpi, dpi] }
    - { role: ramspeed, output: "{{ qtip_results }}/memory", tags: [run, ramspeed, memory] }
  # calculate scores
    - { role: qtip, tasks: calculate, tags: [calculate] }


- hosts: localhost

  roles:
  # aggregate results and produce report
    - { role: qtip, tasks: aggregate, tags: [aggregate] }
  # publish results
    - { role: opnfv-testapi, tasks: report, when: testapi_url is defined, tags: [report] }
