---
services:
  - { name: kibana, upstream: 'http://127.0.0.1:5601' }
  - { name: elastic, upstream: 'http://127.0.0.1:9200' }

qtip_services:
  - { name: restful_api, upstream: 'http://127.0.0.1:5000' }
