##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
heat_template_version: 2015-04-30

description: >
  Used to run VMs for QTIP

parameters:
  image:
    type: string
    description: Name of the image
    default: QTIP_CentOS

  external_net_name:
    type: string
    description: Name of the external network which management network will connect to
    default: admin_floating_net

resources:
  flavor:
    type: OS::Nova::Flavor
    properties:
      ram: 8192
      vcpus: 8
      disk: 80

  network:
    type: OS::Neutron::Net
    properties:
      name: qtip_net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: qtip_subnet
      ip_version: 4
      cidr: 192.168.0.0/24
      network: { get_resource: network }
      dns_nameservers: [8.8.8.8]

  management_router:
    type: OS::Neutron::Router
    properties:
      name: qtip_router
      external_gateway_info:
        network: { get_param: external_net_name }

  management_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: management_router }
      subnet: { get_resource: subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: qtip_security_group
      rules:
          - port_range_min: 22
            port_range_max: 5201
            protocol: tcp
          - port_range_min: 22
            port_range_max: 5201
            protocol: udp
          - protocol: icmp

outputs:
  description: 'none'
