##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# zhihui.wu1@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Cleaning tempT
      file:
        path: '{{ ansible_env.HOME }}/tempT'
        state: absent

    - name: Cleaning qtip_result
      file:
        path: '{{ ansible_env.HOME }}/qtip_result'
        state: absent


