##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# zhihui.wu1@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Make whetstone directories
  file:
    path: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/whetstone/'
    state: directory

- include: ../inxi.yaml
  vars:
    dest_path: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/whetstone/'

- include: ../top.yaml
  vars:
    dest_path: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/whetstone/'

- name: Run whetstone
  shell: ./Run -v whetstone
  args:
    chdir: '{{ ansible_env.HOME }}/tempT/UnixBench/'

- name: Copying result to qtip result directory
  shell: '{{ item }}'
  with_items:
    - mv ~/tempT/UnixBench/results/*.log ./
    - mv ~/tempT/UnixBench/results/*.html ./
    - mv ~/tempT/UnixBench/results/* ./whetstone
  args:
    chdir: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/whetstone/'

- name: Fetch whetstone result files to local manchine
  synchronize:
    mode: pull
    src: '{{ ansible_env.HOME }}/qtip_result/'
    dest: '{{ result_dir }}/'
