##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

qtip_resources: "{{ qtip_package }}/resources"
qtip_reports: reports
qtip_fixtures: fixtures
qtip_dump: dump
qtip_cache: .cache

testapi_url: http://localhost:8000/api/v1
project_name: qtip
case_name: compute
pod_name: qtip-pod
installer: "{{ installer }}"
version: master
scenario: demo

installer_master: "{{ installer_master }}"
installer_master_group:
  fuel: fuel-masters
  apex: apex-underclouds
