##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Get current timestamp
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"

    - name: Checking home directory
      shell: echo $HOME
      register: home_dir

    - name: Fetch hostname
      shell: hostname
      register: host_name

    - name: Make some directories needed
      file:
        path: '{{ home_dir.stdout }}/qtip_result/{{ timestamp }}/{{ host_name.stdout }}'
        state: directory

    - name: Run autogen
      shell: ./autogen.sh
      args:
        chdir: '{{ home_dir.stdout }}/tempD/nDPI/'

    - name: Configure Dpi
      shell: ./configure
      args:
        chdir: '{{ home_dir.stdout }}/tempD/nDPI/'

    - name: Make Dpi
      shell: make
      args:
        chdir: '{{ home_dir.stdout }}/tempD/nDPI/'

    - name: Fetching Test_pcap file
      get_url:
        url: http://build.opnfv.org/artifacts.opnfv.org/qtip/utilities/test.pcap
        dest: '{{ home_dir.stdout }}/tempD/nDPI/example/test.pcap'

    - name: Fetch Averaging script
      copy:
        src: ./dpi_average.sh
        dest: '{{ home_dir.stdout }}/tempD/nDPI/example'
        mode: 777

    - include: ../inxi.yaml

    - include: ../top.yaml

    - name: Run nDPI benchmark
      shell: ./dpi_average.sh
      args:
        chdir: '{{ home_dir.stdout }}/tempD/nDPI/example/'

    - name: Copying result to qtip result directory
      shell: cp $HOME/tempD/nDPI/example/dpi_dump.txt ./
      args:
        chdir: '{{ home_dir.stdout }}/qtip_result/{{ timestamp }}/{{ host_name.stdout }}'

    - name: Copy top log to qtip result directory
      shell: mv $HOME/qtip_result/top.log ./
      args:
        chdir: '{{ home_dir.stdout }}/qtip_result/{{ timestamp }}/{{ host_name.stdout }}'

    - name: Copy inxi log to qtip result directory
      shell: mv $HOME/qtip_result/inxi.log ./
      args:
        chdir: '{{ home_dir.stdout }}/qtip_result/{{ timestamp }}/{{ host_name.stdout }}'

    - name: Fetch result files to local manchine
      synchronize:
        mode: pull
        src: '{{ home_dir.stdout }}/qtip_result/'
        dest: '{{ result_dir }}/dpi/logs/'
