##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Making Dpi directory
      file:
        path: '{{ result_dir }}/'
        state: directory

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Cleaning tempD directory
      file:
        path: '{{ ansible_env.HOME }}/tempD'
        state: absent

    - name: Cleaning qtip_result directory
      file:
        path: '{{ ansible_env.HOME }}/qtip_result'
        state: absent

    - include: ../prepare_env.yaml

    - name: Installing nDPI dependencies if CentOS
      yum:
        name: '{{ item }}'
        state: present
      when: ansible_os_family == "RedHat"
      with_items:
        - git
        - gcc
        - patch
        - perl-Time-HiRes
        - autofconf
        - automake
        - libpcap-devel libtool

    - name: Installing nDPI dependencies if Ubuntu
      apt:
        name: '{{ item }}'
        state: present
      when: ansible_os_family == "Debian"
      with_items:
        - git
        - gcc
        - patch
        - autoconf
        - automake
        - libpcap-dev
        - libtool

    - name: Making nDPI temporary directory
      file:
        path: '{{ ansible_env.HOME }}/tempD'
        state: directory

    - name: Clone nDPI
      git:
        repo: https://github.com/ntop/nDPI.git
        dest: '{{ ansible_env.HOME }}/tempD/nDPI'

    - name: Run autogen && configure Dpi && make Dpi
      command: '{{ item }}'
      with_items:
        - ./autogen.sh
        - ./configure
        - make
      args:
        chdir: '{{ ansible_env.HOME }}/tempD/nDPI/'

    - name: Fetching Test_pcap file
      get_url:
        url: http://build.opnfv.org/artifacts.opnfv.org/qtip/utilities/test.pcap
        dest: '{{ ansible_env.HOME }}/tempD/nDPI/example/test.pcap'

    - name: Fetch Averaging script
      copy:
        src: ./dpi_average.sh
        dest: '{{ ansible_env.HOME }}/tempD/nDPI/example'
        mode: 777