##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- hosts: localhost

  roles:
    - { role: qtip, tasks: setup-local, tags: [setup] }
    - { role: storperf, output: "{% raw %}{{ qtip_results }}{% endraw %}/current/storperf" }

- hosts: SUT
  roles:
    - { role: qtip, tasks: setup-node, tags: [setup] }
    - { role: ceph-info, output: "{% raw %}{{ qtip_results }}{% endraw %}/ceph-info" }
